### ISSUE TITLE
Epic: Refactor Nitro into a standalone inference service on top of Llama.cpp, compatible with Jan

### ISSUE THREAD

**Issue by 0xSage** [janhq/nitro#18]
# Deliverable

- [ ] `janhq/nitro` Github Repo janhq/nitro#20
- [ ] Nitro documentation with overview and installation janhq/jan#113
- [ ] **Stretch goal**: endpoint `/models` returns a list of models that have been downloaded & are ready to be used

## Owners

- @vuonghoainam @tikikun 
- @louis-jan (on the Jan side)

# Big Picture 

- Jan can take in a Nitro server URL
- Nitro can run on Apple Silicon (GGUF, can drop GGML)
- Nitro can run on Nvidia GPUs (with llama.cpp) 
- We are a `.cpp` compatible server

## Exclusions

- Focus on Llama.cpp first, we will tackle TensorRT in subsequent sprint (align with our DGX cluster arriving)

**Comment by tikikun** [comment]
close since we already seperate this into detail issue for llama cpp (ggml) integration. also this original issue is adhoc issue for temporary llama-cpp-python
