### ISSUE TITLE
chore: "Why Nitro" Documentation

### ISSUE THREAD

**Issue by dan-jan** [janhq/nitro#94]
## Tasks

- [ ] Why should I use Nitro?
- [ ] How do I debug plugins?
- [ ] Can Nitro do StableDiffusion?
## Internal Discord Convos

- https://discord.com/channels/1107178041848909847/1110587594137403505/1167637276713549894
- https://discord.com/channels/1107178041848909847/1110587594137403505/1167643385536979015

**Comment by 0xSage** [comment]
sort of done, deprecating this outdated issue
